# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    # Look for `requirements.txt` in the `root` directory
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # Add assignees
    reviewers:
      - "gongfuture"
    versioning-strategy: auto


#  - package-ecosystem: "gitsubmodule"
#    directory: "/" # Location of package manifests
#    schedule:
#      interval: "daily"
#
  - package-ecosystem: "github-actions"
    # Look for `requirements.txt` in the `root` directory
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"